<!-- AUTO-GENERATED BY CONTINUITY - DO NOT EDIT BELOW THIS LINE -->

# Project Memory (Auto-generated by Continuity)

This file contains project context and decisions. AI assistants should read this file for context. MCP tools are an optional enhancement for richer interaction when connected.

## Project Context
- **Total Decisions:** 3
- **Known Topics:** auto-scanned, configuration, tooling, architecture, javascript, node, tech-stack, deployment

## Current State
**Repository:** academic-pages
**Project Type:** Node.js Project | JavaScript
**Branch:** master

**Recent Commits:**
- `1cb916e Initial commit`

**Working Tree:**
- ?? .continuity/
- ?? .cursorrules
- ?? .github/copilot-instructions.md
- ?? .mcp.json
- ?? AGENTS.md
- ?? CLAUDE.md
- ?? GEMINI.md
- ?? SESSION_HANDOFF.md


## Operating Contract
1. **Load context, then search before you change.** MCP-capable agents: call `get_quick_context` at session start, then `search_decisions` before proposing changes. Shell/CLI-only agents (e.g. Copilot): run `continuity context`, then `continuity search "<topic>"` (`grep -i "<topic>" .continuity/decisions.jsonl` if the CLI is unavailable). Name any conflict with a prior decision and let the user choose. **When a prior decision informs your answer, cite it inline — "per decision-abc123, we chose X because Y" — so the user can see the memory being used, not just trust that it was.** `search_decisions` returns a `sourceTag` per result; use it.
2. **Log every deliberate change, immediately.** After each change — not batched — `continuity log "question" "answer" --tags ...`. The trigger is the change, not the commit; include the commit hash in both fields when one exists. Don't ask permission; installing Continuity is the opt-in. Tell the user you logged it.
3. **Track session state.** Edit `.continuity/SESSION_NOTES.md` for goals/blockers and an end-of-session summary.
4. **Recover & be transparent.** If you notice unlogged earlier changes, pause, log them retroactively, and say so.

## Logging paths
- MCP connected: `log_decision` / `search_decisions` / `get_quick_context` / `update_session_notes` — prefer these; they exercise the production path.
- MCP down: `continuity log "question" "answer" --tags a,b` — the always-works fallback.
- Forward work → `continuity task ...` (new ticket); in-flight note → `continuity note ...` (comment on current ticket). Don't cross-pollute.

---

## Project Instructions

# Project Instructions

Describe how this repository prefers to work with AI assistants.


---

## Recent Decisions
1. **decision-msa14zfw** (01/08/2026) [auto-scanned, configuration]
   - Q: Why use GitHub Actions for CI/CD?
   - A: Detected .github/workflows/ directory. GitHub Actions automates testing, building, and deployment pipelines.

2. **decision-msa14zfm** (01/08/2026) [auto-scanned, configuration]
   - Q: Why use Docker for containerization?
   - A: Detected Dockerfile. Docker provides reproducible builds and consistent runtime environments.

3. **decision-msa14zfb** (01/08/2026) [architecture, auto-scanned]
   - Q: Why use Node.js with JavaScript?
   - A: We chose Node.js for its event-driven architecture and npm ecosystem. Key dependencies: none detected.

---

*Auto-generated by Continuity | Updated: 2026-08-01*

<!-- END CONTINUITY AUTO-GENERATED CONTENT -->
